#!/bin/bash

set -e
version=1.0.2-2026.07.04
# Grab yt-dlp version.
release_name=yt-dlp-macos-legacy-v$version

# ffmpeg static downloads uses https://evermeet.cx. Since this site deleted older snapshots for commit-specific compilations: https://deolaha.ca/pub/ffmpeg/snapshots/ need to use a 'release' that is older then the cut off date to work. ffmpeg-7.0.2.zip with upload date of 2024-08-03 08:16 is before the last Mac OS X 10.9 commit-specific release: ffmpeg-116991-ga15d2fdfd9 - 2024-09-11 so I'll go with that. Found on https://deolaha.ca/pub/ffmpeg.
# Current release requires Mac OS X 10.13 - https://evermeet.cx/ffmpeg/getrelease/zip.

ffmpeg_dl=https://deolaha.ca/pub/ffmpeg/ffmpeg-7.0.2.zip

rm -rf $release_name*

if [[ "$1" == "clean" ]]; then
    exit 1
fi

# When this script exits, automatically delete the temp directory.
cleanup()
{
    if [[ -e "$tmp" ]]; then
        rm -r "$tmp"
    fi
}
trap cleanup EXIT

# Put temp directory in /var/tmp to guarantee enough space.
tmp=$(mktemp -d /var/tmp/yt-dlp-macos-legacy.XXXXXX)

# Find new ports.
sudo port -N selfupdate

# Upgrade anything outdated to latest.
sudo port -N upgrade outdated

# Make sure build deps installed.
sudo port -N install yt-dlp curl python314

# Get latest ffmpeg static.
curl -L "$ffmpeg_dl" -o $tmp/ffmpeg.zip
unzip $tmp/ffmpeg.zip -d $tmp

# Remove code signature from ffmpeg.
codesign --remove-signature $tmp/ffmpeg

# Remove quarintine from ffmpeg if it has it.
xattr -d com.apple.quarantine $tmp/ffmpeg > /dev/null 2>&1 || true

# Update if needed, current one as of right now...
sudo port select --set python3 python314

# Set up virtual environment in temp.
virtual_env=$tmp/env
python3 -m venv $virtual_env
source $virtual_env/bin/activate

# Install in virtual environment.
pip install --upgrade pip
pip install pyinstaller yt-dlp mutagen pycryptodomex brotli certifi

# Nothing can be signed when going into pyinstaller, but these are already ad hoc from Macports. Ugly hack, but this has wasted too much of my time.
cp -v osx.py.modified $virtual_env/lib/python3.14/site-packages/PyInstaller/utils/osx.py

# SSL Certs.
certifi_cert_bundle=$(python3 -c "import certifi; print(certifi.where())")

# Runtime hooks to automatically set the SSL path and point to ffmpeg at startup.
hook=$tmp/pyi_ssl_hook.py

# Write hook.
cat << 'EOF' > $hook
import os
import sys

# PyInstaller extracts everything to sys._MEIPASS at runtime
if hasattr(sys, '_MEIPASS'):
    # SSL cert.
    cert_path = os.path.join(sys._MEIPASS, 'cacert.pem')
    os.environ['SSL_CERT_FILE'] = cert_path
    os.environ['WEBSOCKET_CLIENT_CA_BUNDLE'] = cert_path

    # Point to internal binaries for FFmpeg.
    os.environ['PATH'] = sys._MEIPASS + os.pathsep + os.environ.get('PATH', '')
EOF

# Write spec file.
cat << EOF > $tmp/yt-dlp.spec
# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['$(which yt-dlp)'],
    binaries=[
        ('$tmp/ffmpeg', '.'),
    ],
    datas=[
        ('$certifi_cert_bundle', '.'),
    ],
    noarchive=False,
    runtime_hooks=['$hook'], # Points to your custom script
    codesign_identity='',      # ADDED HERE: Force ad-hoc for all binary dependencies
    codesign_options=[],        # ADDED HERE: Strips runtime option from internal cached .so files
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries, # Positions Python internal .so files here
    a.datas,
    [],
    name='yt-dlp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    target_arch='x86_64',       # Added quotes around the string
    #codesign_identity='',      # Force ad-hoc
    codesign_options=[],        # Strips out --options=runtime to fix crash
)
EOF

# Move bincache to deletable tmp. Pyinstaller keeps this around for dumb reasons.
mkdir $tmp/cache
export PYINSTALLER_CONFIG_DIR=$tmp/cache
pyinstaller \
    --workpath $virtual_env/build \
    --distpath $virtual_env \
    $tmp/yt-dlp.spec

# Close virtual enviorement.
deactivate

cd "$(dirname "$0")"

# Gen release.
mkdir $release_name
mv $virtual_env/yt-dlp $release_name

cp -v *.md $release_name
chmod -R 777 $release_name
zip -r $release_name.zip $release_name


